### ISSUE TITLE
Add definition for authentication on function app

### ISSUE THREAD

**Issue by bt-catena** [shibayan/terraform-azurerm-keyvault-acmebot#10]
To enable authentication after deployment through terraform you have to manually enable the authentication on the function app or fork this module and add it yourself.
It is possible to add an auth_settings block on the function app as described in [Function App Argument Reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#argument-reference)
From my point of view this would be a nice feature which I would implement either here as PR or as a fork, any comments ?

**Comment by rudolphjacksonm** [comment]
I think this is related but not sure, so I'll mention this here. @shibayan since `MICROSOFT_PROVIDER_AUTHENTICATION_SECRET` isn't in the state, Terraform proposes to remove it when we run a `terraform plan`. Will this break Acmebot?

**Comment by AppElent** [comment]
Hi @davidkarlsen and @bt-catena did you ever made this work? I am already struggling for days with this. Because you add the authentication after deployment, terraform will make it undone. The auth_settings block doesnt seem like enough for me. In the discussion (this repo) I posted some info. Do you have a working example?

**Comment by davidkarlsen** [comment]
This works:
```
app_settings = {
    MICROSOFT_PROVIDER_AUTHENTICATION_SECRET = var.certbot_auth_secret
  }
  auth_settings = {
    enabled                       = true
    issuer                        = "https://sts.windows.net/${data.azurerm_client_config.core.tenant_id}/v2.0"
    token_store_enabled           = true
    unauthenticated_client_action = "RedirectToLoginPage"
    active_directory = {
      allowed_audiences = ["api://${var.certbot_client_id}"]
      client_id         = var.certbot_client_id
    }
  }
```

you might want to use `allowed_ip_addresses` too, to restrict ranges logging in

**Comment by AppElent** [comment]
Hero! I was close. Do you also have a snippet on how to create the app registration? Or didnt you do that with tf?

**Comment by AppElent** [comment]
@davidkarlsen Well it doesnt seem to work. Its now complaining about auth v2:
`"Message":"Cannot execute the request for site func-appelent-acmebot because the site is running on auth version
│ v2."},{"Code":"BadRequest"},`
Did you create the app registration manually?
