### ISSUE TITLE
Azure Error for empty Acmebot:Webhook

### ISSUE THREAD

**Issue by robincher** [shibayan/terraform-azurerm-keyvault-acmebot#18]
Hi,

I have use this terraform and its all good.  This might be related #15 closed previously.

It seems like Azure will verify if the default Acmebot:Webhook is a valid convention, so setting it as a default "" empty string might cause the function app to stopped working after awhile. 

I am getting this error from the function app after sometime.

```
Microsoft.Extensions.Options: DataAnnotations validation failed for members: 'Webhook' with the error: 'The Webhook field is not a valid fully-qualified http, https, or ftp URL.'.
```

Perhaps we should set var.webhook_url as a mandatory variable?

**Comment by shibayan** [comment]
Fixed in `v1.2.8`
