### ISSUE TITLE
Deprecated Resource

### ISSUE THREAD

**Issue by durandguru** [shibayan/terraform-azurerm-keyvault-acmebot#33]
I get the following warning (Terraform 1.2.8 / AzureRM 3.21.0):

 Warning: Deprecated Resource
│
│   with module.keyvault_acmebot.azurerm_app_service_plan.serverfarm,
│   on .terraform\modules\keyvault_acmebot\main.tf line 13, in resource "azurerm_app_service_plan" "serverfarm":
│   13: resource "azurerm_app_service_plan" "serverfarm" {
│
│ The `azurerm_app_service_plan` resource has been superseded by the `azurerm_service_plan` resource. Whilst this resource will continue to be available in the 2.x and 3.x  
│ releases it is feature-frozen for compatibility purposes, will no longer receive any updates and will be removed in a future major release of the Azure Provider.
(and 2 more similar warnings elsewhere)

**Comment by shibayan** [comment]
You will need to update to the v2 module.
https://github.com/shibayan/terraform-azurerm-keyvault-acmebot/releases/tag/v2.0.0
